### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by lpassos** [manub/scalatest-embedded-kafka#57] opened 2016-12-05 21:41 UTC
I keep getting this exception, although I have 16Gb of RAM. Playing with the JVM heap parameters do not seem to help at all.

**Comment by manub** [comment] 2016-12-05 22:51
Hi @lpassos could you elaborate a bit further? E.g. the test that causes this issue.

**Comment by kubum** [comment] 2016-12-11 09:18
Hi @manub 

I accidentally reproduced it when tried to scope my tests, previously I used a constant name for my topic, e.g. "blah". However, if each of my test would use something like ```java.util.UUID.randomUUID.toString``` I would get OOM relatively quickly.

Stack trace:

```scala
java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
	at kafka.log.SkimpyOffsetMap.<init>(OffsetMap.scala:44)
	at kafka.log.LogCleaner$CleanerThread.<init>(LogCleaner.scala:196)
	at kafka.log.LogCleaner$$anonfun$2.apply(LogCleaner.scala:86)
	at kafka.log.LogCleaner$$anonfun$2.apply(LogCleaner.scala:86)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Range.foreach(Range.scala:166)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at kafka.log.LogCleaner.<init>(LogCleaner.scala:86)
	at kafka.log.LogManager.<init>(LogManager.scala:66)
	at kafka.server.KafkaServer.createLogManager(KafkaServer.scala:647)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:209)
	at net.manub.embeddedkafka.EmbeddedKafkaSupport$class.startKafka(EmbeddedKafka.scala:294)
	at net.manub.embeddedkafka.EmbeddedKafka$.startKafka(EmbeddedKafka.scala:36)
	at net.manub.embeddedkafka.EmbeddedKafka$.start(EmbeddedKafka.scala:48)
```

It feels like it is not cleaning logs property on shutdown, but I am not sure how to set it.

Do you have any ideas @manub?

**Comment by manub** [comment] 2016-12-11 18:04
The logs directories are marked as temp and deleted on JVM exit, but this is not the case when executing multiple tests inside the same JVM. I'll publish a fix for this.

**Comment by manub** [comment] 2016-12-11 18:33
@lpassos @kubum I merged this change on master, could you please try to build master on your machine and see if you get the same behaviour?

**Comment by kubum** [comment] 2016-12-11 19:55
Hi @manub 

You made me look into the repo :)

Unfortunately, your fix didn't work for me and I continued looking and found the solution. Please have a look at my PR. It looks like similar happened to Kafka integration tests.

Thanks for your help!

Let me know what you think

**Comment by manub** [comment] 2016-12-11 20:01
Awesome - that's great. I'll close this issue and will release in the upcoming days.

**Comment by manub** [comment] 2016-12-11 20:01
Thanks @kubum !

**Closed by manub** 2016-12-11 20:01 UTC

**Comment by kubum** [comment] 2016-12-11 20:04
Thanks @manub !

By the way, do you know if there is an elegant way to boot a single instance of kafka for whole suite instead of using AfterAll / BeforeAll? It would overall improve speed of whole suite and I can scope tests by using different topics.

**Comment by manub** [comment] 2016-12-11 20:12
Have you tried having a look at http://www.scalatest.org/user_guide/sharing_fixtures? I don't know on top of my head. 

I'd argue that probably you want to have a new instance of Kafka for some tests in order to start for a clean situation - but of course YMMV!
